security:
  oauth2:
    client:
      client-id: myClient1
      client-secret: mySecret
      user-authorization-uri: http://localhost:8282/oauth/authorize
      access-token-uri: http://localhost:8282/oauth/token
    resource:
      token-info-uri: http://localhost:8282/oauth/check_token
server:
  port: 8284
  servlet:
    session:
      cookie:
        name: KSESSION
